(deftheme Pumpkin
  "Created 2016-12-06.")

(custom-theme-set-faces
 'Pumpkin
 '(cursor ((t (:background "orange1"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "light green"))))
 '(minibuffer-prompt ((t (:background "#282828" :foreground "light green" :weight normal))))
 '(highlight ((t (:background "gray30"))))
 '(region ((t (:background "#30434C"))))
 '(shadow ((t (:foreground "grey70"))))
 '(secondary-selection ((t (:background "#2B3C44"))))
 '(trailing-whitespace ((t (:background "red4"))))
 '(font-lock-builtin-face ((t (:foreground "#FE8019"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#7C6F64"))))
 '(font-lock-constant-face ((t (:foreground "Orange"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#A89984" :slant oblique))))
 '(font-lock-keyword-face ((t (:foreground "#DD6F48"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#528B8B"))))
 '(font-lock-type-face ((t (:foreground "#66999D"))))
 '(font-lock-variable-name-face ((t (:foreground "#83A598"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#FB4934"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#83A598"))))
 '(link-visited ((t (:underline nil :foreground "#83A598"))))
 '(fringe ((t (:background "#282828"))))
 '(header-line ((t (:weight normal :foreground "#61ACBB" :background "#282828"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box nil :foreground "#EBDBB2" :background "#1D2021"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#A89984" :background "#504945"))))
 '(isearch ((t (:foreground "#FDF4C1" :background "#427B58"))))
 '(isearch-fail ((t (:foreground "#FFFFC8" :background "#9D0006"))))
 '(lazy-highlight ((t (:foreground "#FDF4C1" :background "#504945"))))
 '(match ((t (:foreground "#FDF4C1" :background "#504945"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :stipple nil :background "#282828" :foreground "DarkGoldenrod1" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "nil" :family "Menlo")))))

(provide-theme 'Pumpkin)
